version: '2'
services:
  kafka:
    image: 'confluentinc/confluent-local:7.8.0'
    container_name: kafka
    ports:
      - '9092:9092'
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost 
  influxdb:
    image: 'influxdb:1.11.8'
    container_name: influxdb
    ports:
      - '8086:8086'
    environment:
      INFLUXDB_DB: last_stone_weight
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: admin
      INFLUXDB_USER: user
      INFLUXDB_USER_PASSWORD: password
    depends_on:
      - kafka
  grafana:
    image: 'grafana/grafana:11.4.0'
    container_name: grafana
    ports:
      - '3000:3000'
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    depends_on:
      - influxdb